import type * as Preset from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";
import { themes as prismThemes } from "prism-react-renderer";
import rehypeKatex from "rehype-katex";
import remarkBreaks from "remark-breaks";
import remarkCodeImport from "remark-code-import";
import remarkMath from "remark-math";
import path from "path";

const config: Config = {
  title: "heliannuuthus",
  tagline: "heliannuuthus",
  favicon: "img/favicon.ico",

  // Set the production url of your site here
  url: "https://heliannuuthus.github.io/",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "heliannuuthus", // Usually your GitHub org/user name.
  projectName: "heliannuuthus.github.io", // Usually your repo name.
  trailingSlash: false,

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },
  markdown: {
    mermaid: true,
    parseFrontMatter: async (params) => {
      // Reuse the default parser
      if (params.filePath.includes("/terms/")) {
        return {
          frontMatter: {
            slug: path.relative(
              "blog",
              params.filePath.replace(/^blog/, "").replace(/\.mdx?$/, ""),
            ),
            title: `${path.basename(
              params.filePath,
              path.extname(params.filePath),
            )}-terminology`,
            authors: ["robot"],
            description: `This is a terminology generated by code logic.`,
            unlisted: true,
          },
          content: params.fileContent,
        };
      }
      const result = await params.defaultParseFrontMatter(params);
      if (params.filePath.includes("/glossary.md")) {
        return {
          frontMatter: {
            slug: "glossary",
            title: "Glossary",
            authors: ["robot"],
            description: `This is a glossary generated by code logic.`,
          },
          content: result.content,
        };
      }

      if (
        [`/_contents/`, `/_partials/`].some((path) =>
          params.filePath.includes(path)
        )
      ) {
        result.frontMatter = {};
        return result;
      }

      result.frontMatter.description =
        result.frontMatter.description?.replaceAll("{{MY_VAR}}", "MY_VALUE");

      // Create your own front matter shortcut
      if (result.frontMatter.i_do_not_want_docs_pagination) {
        result.frontMatter.pagination_prev = null;
        result.frontMatter.pagination_next = null;
      }

      // Rename an unsupported front matter coming from another system
      if (result.frontMatter.cms_seo_summary) {
        result.frontMatter.description = result.frontMatter.cms_seo_summary;
        delete result.frontMatter.cms_seo_summary;
      }
      return result;
    },
  },
  themes: ["@docusaurus/theme-mermaid"],
  presets: [
    [
      "classic",
      {
        docs: false,
        blog: {
          remarkPlugins: [remarkCodeImport, remarkBreaks, remarkMath],
          rehypePlugins: [rehypeKatex],
          blogSidebarTitle: "最近的发布",
          routeBasePath: "/",
          showReadingTime: true,
          showLastUpdateAuthor: true,
          showLastUpdateTime: true,
          feedOptions: {
            type: ["rss", "atom"],
            xslt: true,
          },
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            "https://github.com/heliannuuthus/heliannuuthus.github.io/tree/master/",
          // Useful options to enforce blogging best practices
          onInlineTags: "warn",
          onInlineAuthors: "warn",
          onUntruncatedBlogPosts: "warn",
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],
  plugins: [
    [
      require.resolve("heliannuuthus-docusaurus-terminology"),
      {
<<<<<<< HEAD
        termsDir: "blog/terms",
        glossaryDir: "blog",
        glossaryFilepath: "blog/glossary.md",
=======
        termsDir: "./blog/terms",
<<<<<<< HEAD
        docsDir: "blog",
        glossaryFilepath: "./blog/glossary.md",
>>>>>>> 75c836d (cc)
        termPreviewComponentPath: "@site/src/components/TermPreview.tsx",
        glossaryComponentPath: "@site/src/components/Glossary.tsx",
=======
        docsDir: "./blog",
        glossaryFilepath: "./blog/glossary.md",
        termPreviewComponentPath: "@site/src/components/TermPreview.tsx",
>>>>>>> 137c798 (cc)
      },
    ],
    ["./plugins/authors-list/index.js", { path: "./blog/authors.yml" }],
  ],
  themeConfig: {
    navbar: {
      title: "heliannuuthus",
      logo: {
        alt: "heliannuuthus",
        src: "img/logo.svg",
      },
      items: [
        {
          href: "https://github.com/heliannuuthus",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 5,
    },
    footer: {
      style: "dark",
      copyright: `Copyright © ${new Date().getFullYear()} heliannuuthus. Built with Docusaurus.`,
    },
    prism: {
      additionalLanguages: ["java", "javadoc", "rust", "go", "bash", "python"],
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      magicComments: [
        {
          className: "theme-code-block-highlighted-line",
          line: "highlight-next-line",
          block: { start: "highlight-start", end: "highlight-end" },
        },
        {
          className: "code-block-important",
          line: "important line",
        },
      ],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
