name: Pre Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - master

jobs:
  pre-deploy:
    name: pre deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install:packages && pnpm install:plugins && pnpm i --frozen-lockfile

      - name: Build website
        run: pnpm build
